[package]
name = "collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "vec_t"
path = "vector/main.rs"

[[bin]]
name = "vecdeque"
path = "vecdeque/main.rs"
